[advisories]
# Ignore unfixable vulnerabilities for now. In new trezoa version
#  it will be fixed.
ignore = ["RUSTSEC-2024-0344", "RUSTSEC-2022-0093"]

[output]
deny = [] # exit on error if unmaintained dependencies are found
format = "terminal" # "terminal" (human-readable report) or "json"
quiet = true # Only print information on error
show_tree = true # Show inverse dependency trees along with advisories (default: true)
