name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  SOLANA_VERSION: "1.18.9"
  RUST_STABLE_VERSION: "1.78.0"

defaults:
  run:
    working-directory: ./

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install stable Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE_VERSION }}
          components: clippy
          cache: true

      - name: Install nightly Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          cache: true

      - name: Set default Rust toolchain
        run: |
          rustup show 
          rustup override set ${{ env.RUST_STABLE_VERSION }}

      - name: Run fmt
        run: cargo +nightly fmt -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features --workspace --exclude rewards -- -D warnings

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev

      - name: Install stable Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_STABLE_VERSION }}
          cache: true

      - name: Cache Trezoa binaries
        uses: actions/cache@v2
        with:
          path: ~/.cache/trezoa
          key: ${{ runner.os }}-${{ env.RUST_STABLE_VERSION }}

      - name: Install Trezoa
        run: |
          sh -c "$(curl -sSfL https://release.trezoa.com/v${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/trezoa/install/active_release/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/share/trezoa/install/active_release/bin:$PATH"
          trezoa --version
          echo "Generating keypair..."
          trezoa-keygen new -o "$HOME/.config/trezoa/id.json" --no-passphrase --silent

      - name: Switch toolchain
        run: |
          rustup override set ${{ env.RUST_STABLE_VERSION }}
          trezoa-install init ${{ env.SOLANA_VERSION }}

      - name: Run tests
        run: cargo test-bpf
